- type: entity
  id: SquadBase
  abstract: true
  components:
  - type: SquadTeam
    background:
      sprite: _RMC14/Interface/cm_job_icons.rsi
      state: hudsquad
    maxRoles:
      CMSquadLeader: 1
      CMFireteamLeader: 2
      CMWeaponsSpecialist: 1
      CMSmartGunOperator: 1
      CMCombatTech: 3
      CMHospitalCorpsman: 4

- type: entity
  parent: SquadBase
  id: SquadAlpha
  name: "Альфа"
  components:
  - type: SquadTeam
    roundStart: true
    color: "#E61919"
    accessLevels:
    - CMAccessAlpha

- type: entity
  parent: SquadBase
  id: SquadBravo
  name: "Браво"
  components:
  - type: SquadTeam
    roundStart: true
    color: "#FFC32D"
    accessLevels:
    - CMAccessBravo

- type: entity
  parent: SquadBase
  id: SquadCharlie
  name: "Чарлі"
  components:
  - type: SquadTeam
    roundStart: true
    color: "#C864C8"
    accessLevels:
    - CMAccessCharlie

- type: entity
  parent: SquadBase
  id: SquadDelta
  name: "Дельта"
  components:
  - type: SquadTeam
    roundStart: true
    color: "#4148C8"
    accessLevels:
    - CMAccessDelta

- type: entity
  parent: SquadBase
  id: SquadEcho
  name: "Ехо"
  components:
  - type: SquadTeam
    color: "#67D692"
    accessLevels:
    - CMAccessAlpha
    - CMAccessBravo
    - CMAccessCharlie
    - CMAccessDelta

- type: entity
  parent: SquadBase
  id: SquadFoxtrot
  name: "Фокстрот"
  components:
  - type: SquadTeam
    color: "#C47A50"
    accessLevels:
    - CMAccessAlpha
    - CMAccessBravo
    - CMAccessCharlie
    - CMAccessDelta
