- type: entity
  parent: BaseItem
  id: AccessConfigurator
  name: "конфігуратор доступу"
  description: "Використовується для зміни вимог до рівня доступу для шлюзів та інших пристроїв, що замикаються."
  components:
    - type: EmitSoundOnLand
      sound:
        path: /Audio/Items/multitool_drop.ogg
    - type: Sprite
      sprite: Objects/Tools/access_configurator.rsi
      state: icon
    - type: Item
      size: Small
    - type: Clothing
      sprite: Objects/Tools/access_configurator.rsi
      quickEquip: false
      slots:
        - Belt
    - type: AccessOverrider
      accessLevels:
      - Armory
      - Atmospherics
      - Bar
      - Brig
      - Detective
      - Captain
      - Cargo
      - Chapel
      - Chemistry
      - ChiefEngineer
      - ChiefMedicalOfficer
      - Command
      - Engineering
      - External
      - HeadOfPersonnel
      - HeadOfSecurity
      - Hydroponics
      - Janitor
      - Kitchen
      - Lawyer
      - Maintenance
      - Medical
      - Quartermaster
      - Research
      - ResearchDirector
      - Salvage
      - Security
      - Service
      - Theatre
      privilegedIdSlot:
        name: id-card-console-privileged-id
        ejectSound: /Audio/Machines/id_swipe.ogg
        insertSound: /Audio/Weapons/Guns/MagIn/batrifle_magin.ogg
        ejectOnBreak: true
        swap: false
        whitelist:
          components:
          - IdCard
      denialSound:
        path: /Audio/Machines/custom_deny.ogg
      doAfter: 0.5
    - type: UserInterface
      interfaces:
        enum.AccessOverriderUiKey.Key:
          type: AccessOverriderBoundUserInterface
    - type: ActivatableUI
      key: enum.AccessOverriderUiKey.Key
      requireHands: true
      requireActiveHand: false
      singleUser: true
    - type: ItemSlots
    - type: ContainerContainer
      containers:
        AccessOverrider-privilegedId: !type:ContainerSlot

- type: entity
  parent: AccessConfigurator
  id: AccessConfiguratorUniversal
  name: "універсальний конфігуратор доступу"
  suffix: Admin
  description: "Модифікований конфігуратор доступу, який використовується лише міфічним Адміністратором."
  components:
  - type: Sprite
    sprite: Objects/Tools/universal_access_configurator.rsi
  - type: Clothing
    sprite: Objects/Tools/universal_access_configurator.rsi
  - type: AccessOverrider
    accessLevels:
    - Armory
    - Atmospherics
    - Bar
    - Brig
    - Detective
    - Captain
    - Cargo
    - Chapel
    - Chemistry
    - ChiefEngineer
    - ChiefMedicalOfficer
    - Command
    - Engineering
    - External
    - HeadOfPersonnel
    - HeadOfSecurity
    - Hydroponics
    - Janitor
    - Kitchen
    - Lawyer
    - Maintenance
    - Medical
    - Quartermaster
    - Research
    - ResearchDirector
    - Salvage
    - Security
    - Service
    - Theatre
    - CentralCommand
    - NuclearOperative
    - SyndicateAgent
    privilegedIdSlot:
      name: id-card-console-privileged-id
      ejectSound: /Audio/Machines/id_swipe.ogg
      insertSound: /Audio/Weapons/Guns/MagIn/batrifle_magin.ogg
      ejectOnBreak: true
      swap: false
      whitelist:
        components:
        - IdCard
    denialSound:
      path: /Audio/Machines/custom_deny.ogg
    doAfter: 0.5
